plugins {
    id 'com.android.application'
}

android {
    namespace 'com.arkforge.faith'
    compileSdk 35

    defaultConfig {
        applicationId 'com.arkforge.faith'
        minSdk 26
        targetSdk 35
        versionCode 230001
        versionName '23.0.0-reader-index-patent-archive'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
